### ISSUE TITLE
Target Tracking

### ISSUE THREAD

**Issue by akj** [achaea-oracle/oracle#14]
#### Is your feature request related to a problem? Please describe.
Right now Oracle has no functionality to track targets.

#### Describe the solution you'd like
Oracle should ideally:

- [ ] Have a table that stores a target's health / mana, class, afflictions, humours, fractures, last direction moved, rebounding status, and possibly shield.
- [ ] Track target class through an alias and by creating a name database.
  [ ] Triggers to capture all other information such as health, mana, rebounding status, etc.
- [ ] offense tracking including afflictions and limbs.

#### Describe alternatives you've considered
None

#### Additional context
Offense tracking will be the most challenging part of this endeavor.
